// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://localhost:3000" | (string & {})
}

export type InnerErrorT = {
  code: string
  innererror?: InnerErrorT
}

export type ErrorObjectT = {
  code:
    | "BadRequest"
    | "Unauthenticated"
    | "Unauthorized"
    | "Forbidden"
    | "NotFound"
    | "MethodNotAllowed"
    | "Conflict"
    | "UnprocessableEntity"
    | "TooManyRequests"
    | "InternalServerError"
    | "ServiceUnavailable"
    | "InsufficientPermissions"
    | "ValidationFailed"
    | "InvalidInput"
    | "MissingRequiredField"
    | "ResourceNotFound"
    | "ResourceAlreadyExists"
    | "ResourceLocked"
    | "OperationFailed"
    | "DataIntegrityViolation"
    | "RateLimitExceeded"
    | string
  message: string
  target?: string
  details?: Array<ErrorObjectT>
  innererror?: InnerErrorT
}

export type ErrorResponseT = {
  error: ErrorObjectT
}

export type GetApiAdminUserTestData = {
  body?: never
  path?: never
  query?: never
  url: "/api/admin/user/test"
}

export type GetApiAdminUserTestResponses = {
  /**
   * Success
   */
  200: {
    [key: string]: unknown
  }
}

export type GetApiAdminUserTestResponse =
  GetApiAdminUserTestResponses[keyof GetApiAdminUserTestResponses]
