/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely"

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>

export type Timestamp = ColumnType<Date, Date | string, Date | string>

export interface Account {
  accessToken: string | null
  expiresAt: Int8 | null
  id: string
  idToken: string | null
  provider: string
  providerAccountId: string
  refreshToken: string | null
  scope: string | null
  sessionState: string | null
  tokenType: string | null
  type: string
  userId: string
}

export interface Session {
  expires: Timestamp
  sessionKey: string
  userId: string
}

export interface User {
  about: string | null
  avatarImageKey: string | null
  bannerImageKey: string | null
  commentKarma: Generated<number>
  createdAt: Generated<Timestamp>
  displayName: string | null
  email: string
  id: string
  image: string | null
  isAdmin: Generated<boolean>
  name: string | null
  postKarma: Generated<number>
  suspendedAt: Timestamp | null
  suspensionReason: string | null
  username: string
}

export interface UserSettings {
  allowFollows: Generated<boolean>
  autoplayMedia: Generated<boolean>
  blurMature: Generated<boolean>
  chatRequestPolicy: Generated<string>
  createdAt: Generated<Timestamp>
  defaultMarkdownEditor: Generated<boolean>
  displayMode: Generated<string>
  feedView: Generated<string>
  openPostsNewTab: Generated<boolean>
  reduceMotion: Generated<boolean>
  safeSearch: Generated<boolean>
  showFollowerCount: Generated<boolean>
  showInSearch: Generated<boolean>
  showMature: Generated<boolean>
  showRecommendations: Generated<boolean>
  userId: string
}

export interface DB {
  account: Account
  session: Session
  user: User
  userSettings: UserSettings
}
