/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely"

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>

export type Timestamp = ColumnType<Date, Date | string, Date | string>

export interface Account {
  accessToken: string | null
  expiresAt: Int8 | null
  id: string
  idToken: string | null
  provider: string
  providerAccountId: string
  refreshToken: string | null
  scope: string | null
  sessionState: string | null
  tokenType: string | null
  type: string
  userId: string
}

export interface Community {
  bannerImageKey: string | null
  createdAt: Generated<Timestamp>
  createdByUserId: string | null
  defaultCommentSort: Generated<string>
  description: string
  displayName: string | null
  iconImageKey: string | null
  id: string
  isNsfw: Generated<boolean>
  memberCount: Generated<number>
  name: string
  topicId: string | null
  visibility: Generated<string>
}

export interface CommunityJoinRequest {
  communityId: string
  createdAt: Generated<Timestamp>
  id: string
  message: string | null
  resolvedAt: Timestamp | null
  resolvedByUserId: string | null
  status: Generated<string>
  userId: string
}

export interface CommunityMember {
  communityId: string
  id: string
  isFavorite: Generated<boolean>
  joinedAt: Generated<Timestamp>
  notificationLevel: Generated<string>
  userId: string
}

export interface CommunityModerator {
  addedAt: Generated<Timestamp>
  communityId: string
  id: string
  permConfig: Generated<boolean>
  permEverything: Generated<boolean>
  permFlair: Generated<boolean>
  permMail: Generated<boolean>
  permPostsComments: Generated<boolean>
  permUsers: Generated<boolean>
  permWiki: Generated<boolean>
  position: number
  userId: string
}

export interface CommunityRule {
  communityId: string
  createdAt: Generated<Timestamp>
  description: string | null
  id: string
  name: string
  position: number
}

export interface CommunityUserFlair {
  communityId: string
  customText: string | null
  id: string
  userFlairTemplateId: string | null
  userId: string
}

export interface PostFlairTemplate {
  bgColor: string | null
  communityId: string
  createdAt: Generated<Timestamp>
  id: string
  modOnly: Generated<boolean>
  position: Generated<number>
  text: string
  textColor: string | null
}

export interface Session {
  expires: Timestamp
  sessionKey: string
  userId: string
}

export interface Topic {
  displayOrder: number
  id: string
  name: string
  slug: string
}

export interface User {
  about: string | null
  avatarImageKey: string | null
  bannerImageKey: string | null
  commentKarma: Generated<number>
  createdAt: Generated<Timestamp>
  displayName: string | null
  email: string
  id: string
  image: string | null
  isAdmin: Generated<boolean>
  name: string | null
  postKarma: Generated<number>
  suspendedAt: Timestamp | null
  suspensionReason: string | null
  username: string
}

export interface UserFlairTemplate {
  bgColor: string | null
  communityId: string
  createdAt: Generated<Timestamp>
  id: string
  modOnly: Generated<boolean>
  position: Generated<number>
  selfAssignable: Generated<boolean>
  text: string
  textColor: string | null
}

export interface UserSettings {
  allowFollows: Generated<boolean>
  autoplayMedia: Generated<boolean>
  blurMature: Generated<boolean>
  chatRequestPolicy: Generated<string>
  createdAt: Generated<Timestamp>
  defaultMarkdownEditor: Generated<boolean>
  displayMode: Generated<string>
  feedView: Generated<string>
  openPostsNewTab: Generated<boolean>
  reduceMotion: Generated<boolean>
  safeSearch: Generated<boolean>
  showFollowerCount: Generated<boolean>
  showInSearch: Generated<boolean>
  showMature: Generated<boolean>
  showRecommendations: Generated<boolean>
  userId: string
}

export interface DB {
  account: Account
  community: Community
  communityJoinRequest: CommunityJoinRequest
  communityMember: CommunityMember
  communityModerator: CommunityModerator
  communityRule: CommunityRule
  communityUserFlair: CommunityUserFlair
  postFlairTemplate: PostFlairTemplate
  session: Session
  topic: Topic
  user: User
  userFlairTemplate: UserFlairTemplate
  userSettings: UserSettings
}
